#!/user/bin/env ruby
begin
  require '../lib/Medbay.rb'
rescue LoadError => e
  require 'rubygems'
  path = File.expand_path '../../lib', __FILE__
  $:.unshift(path) if File.directory?(path) && !$:.include?(path)
  require '../lib/Medbay.rb'
end

Medbay.configure do |config|
  test1 = Medbay::Test.new('Redis', lambda { return true })
  test2 = Medbay::Test.new('MySQL', lambda { return false })
  test3 = Medbay::Test.new('AmazonRDS', lambda { return true })

  config.tests = [test1,test2,test3]
end

Medbay::App.run!
