#!/user/bin/env ruby
begin
  require 'lib/Medbay/app.rb'
rescue LoadError => e
  require 'rubygems'
  path = File.expand_path '../../lib', __FILE__
  $:.unshift(path) if File.directory?(path) && !$:.include?(path)
  require 'lib/Medbay/app.rb'
end

Medbay::App.run
